import React, { useEffect, useMemo, useState } from 'react';
import { getProducts, placeOrder } from './services/api';

const money = value => `$${value.toFixed(2)}`;
function App() {
  const [products, setProducts] = useState([]); const [category, setCategory] = useState('All'); const [search, setSearch] = useState(''); const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('brew-cart') || '[]')); const [view, setView] = useState('home'); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [order, setOrder] = useState(null);
  useEffect(() => { getProducts({ category, search }).then(setProducts).catch(e => setNotice(e.message)).finally(() => setLoading(false)); }, [category, search]);
  useEffect(() => localStorage.setItem('brew-cart', JSON.stringify(cart)), [cart]);
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]); const tax = subtotal * .08;
  const addToCart = product => { setCart(items => { const found = items.find(item => item.id === product.id); return found ? items.map(item => item.id === product.id ? { ...item, quantity: Math.min(item.quantity + 1, 10) } : item) : [...items, { ...product, quantity: 1 }]; }); setNotice(`${product.name} added to your order`); setTimeout(() => setNotice(''), 2400); };
  const updateQty = (id, quantity) => setCart(items => quantity < 1 ? items.filter(item => item.id !== id) : items.map(item => item.id === id ? { ...item, quantity: Math.min(quantity, 10) } : item));
  return <div className="app"><header><button className="brand" onClick={() => setView('home')}><span className="brand-mark">☕</span><span><b>BREW & BLOOM</b><small>COFFEE HOUSE</small></span></button><nav><button onClick={() => setView('home')}>Home</button><button onClick={() => { setView('menu'); setCategory('All'); }}>Menu</button><button onClick={() => setView('about')}>Our story</button></nav><button className="cart-button" onClick={() => setView('cart')}>Order online <span>{cart.reduce((s, i) => s + i.quantity, 0)}</span></button></header>
    {notice && <div className="toast">✓ {notice}</div>}
    {view === 'home' && <Home onMenu={() => setView('menu')} onAdd={addToCart} products={products.filter(p => p.popular).slice(0, 3)} />}
    {view === 'menu' && <main className="menu-page"><div className="page-heading"><p className="eyebrow">THE DAILY POUR</p><h1>Find your perfect cup.</h1><p>Small-batch beans, thoughtful ingredients, and a little joy in every sip.</p></div><div className="filters"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search the menu..." />{['All','Coffee','Tea','Cold','Other'].map(c => <button className={category === c ? 'active' : ''} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div>{loading ? <p className="status">Brewing the menu...</p> : <ProductGrid products={products} onAdd={addToCart} />}</main>}
    {view === 'cart' && <Cart cart={cart} subtotal={subtotal} tax={tax} onQty={updateQty} onCheckout={() => setView('checkout')} onBack={() => setView('menu')} />}
    {view === 'checkout' && <Checkout cart={cart} subtotal={subtotal} tax={tax} onBack={() => setView('cart')} onComplete={async customer => { try { const result = await placeOrder({ customer, items: cart }); setOrder(result); setCart([]); setView('success'); } catch (e) { setNotice(e.message); } }} />}
    {view === 'success' && <section className="success"><div className="success-icon">✓</div><p className="eyebrow">ORDER RECEIVED</p><h1>Thanks for choosing good coffee.</h1><p>Your order <b>#{order?.id}</b> is being prepared. We’ll have it ready shortly.</p><button className="primary" onClick={() => setView('menu')}>Back to the menu</button></section>}
    {view === 'about' && <section className="story"><p className="eyebrow">OUR STORY</p><h1>Good coffee tastes better together.</h1><p>We started Brew & Bloom with a simple idea: make the neighborhood’s favorite coffee house feel like your favorite place to be. Every drink is made to order with carefully sourced beans and genuinely warm service.</p><button className="primary" onClick={() => setView('menu')}>Explore the menu</button></section>}<footer><span>© 2025 Brew & Bloom</span><span>Made for slow mornings & good conversations.</span></footer></div>
}
function Home({ onMenu, onAdd, products }) { return <><section className="hero"><div><p className="eyebrow">COFFEE FOR YOUR RITUAL</p><h1>Pause. Sip.<br/><i>Bloom.</i></h1><p className="hero-copy">Thoughtfully crafted coffee and drinks for the moments that matter.</p><button className="primary" onClick={onMenu}>Explore the menu <span>→</span></button></div><div className="hero-image"><div className="image-note">EST. 2018<br/><b>ROASTED<br/>WITH LOVE</b></div></div></section><section className="featured"><div className="section-title"><div><p className="eyebrow">FAN FAVORITES</p><h2>Made for your mood.</h2></div><button onClick={onMenu} className="text-button">View all drinks →</button></div><ProductGrid products={products} onAdd={onAdd} /></section></> }
function ProductGrid({ products, onAdd }) { return <div className="product-grid">{products.map(p => <article className="product-card" key={p.id}><div className="product-image"><img src={p.image} alt={p.name}/><span>{p.category}</span></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.description}</p></div><div className="product-bottom"><b>{money(p.price)}</b><button onClick={() => onAdd(p)}>+ Add</button></div></div></article>)}</div> }
function Cart({ cart, subtotal, tax, onQty, onCheckout, onBack }) { return <main className="cart-page"><button className="back" onClick={onBack}>← Back to menu</button><h1>Your order</h1>{!cart.length ? <div className="empty"><div>☕</div><h2>Your cart is waiting.</h2><p>Add something delicious to get started.</p><button className="primary" onClick={onBack}>Browse drinks</button></div> : <div className="cart-layout"><div>{cart.map(item => <div className="cart-item" key={item.id}><img src={item.image} alt=""/><div><h3>{item.name}</h3><p>{money(item.price)} · {item.category}</p><div className="qty"><button onClick={() => onQty(item.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button onClick={() => onQty(item.id, item.quantity + 1)}>+</button></div></div><b>{money(item.price * item.quantity)}</b></div>)}</div><aside className="summary"><h2>Order summary</h2><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Tax</span><b>{money(tax)}</b></p><hr/><p className="total"><span>Total</span><b>{money(subtotal + tax)}</b></p><button className="primary full" onClick={onCheckout}>Continue to checkout →</button></aside></div>}</main> }
function Checkout({ cart, subtotal, tax, onBack, onComplete }) { const [form, setForm] = useState({ name: '', email: '', address: '', notes: '' }); const [error, setError] = useState(''); const submit = e => { e.preventDefault(); if (!form.name || !form.email.includes('@') || !form.address) return setError('Please complete your name, email, and pickup details.'); onComplete(form); }; return <main className="checkout"><button className="back" onClick={onBack}>← Back to order</button><div className="checkout-grid"><form onSubmit={submit}><p className="eyebrow">ALMOST THERE</p><h1>Let's make it yours.</h1>{error && <div className="error">{error}</div>}<label>Name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})} placeholder="Your name" /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({...form, email:e.target.value})} placeholder="you@example.com" /></label><label>Pickup details<input required value={form.address} onChange={e => setForm({...form, address:e.target.value})} placeholder="Pickup time or address" /></label><label>Anything else? <span>(optional)</span><textarea value={form.notes} onChange={e => setForm({...form, notes:e.target.value})} placeholder="Extra oat milk, please..." /></label><button className="primary full">Place order · {money(subtotal + tax)}</button></form><aside className="summary checkout-summary"><h2>In your cup</h2>{cart.map(i => <p key={i.id}><span>{i.quantity} × {i.name}</span><b>{money(i.price*i.quantity)}</b></p>)}<hr/><p className="total"><span>Total</span><b>{money(subtotal+tax)}</b></p><small>Payment is collected at pickup for this demo.</small></aside></div></main> }
export default App;
